/*
*  Armadillo Workflow Platform v1.0
*  A simple pipeline system for phylogenetic analysis
*
*  Copyright (C) 2009-2011  Etienne Lord, Mickael Leclercq
*
*  This program is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 3 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package editors;


import biologic.seqclasses.InformationJDialog;
import biologic.*;
import configuration.BlastDBFilter;
import javax.swing.SwingWorker;
import workflows.workflow_properties;
import configuration.Config;
import database.databaseFunction;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import editor.EditorInterface;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import workflows.armadillo_workflow;
import workflows.workflow_properties_dictionnary;

/**
 * Editor of the object properties in the Main Workflow
 * Note: Only called if object doesnt have a Custum Editor
 * @author Etienne Lord
 * @since July 2009
 */
public class loadFiles2Editor extends javax.swing.JDialog implements EditorInterface {
    
    ////////////////////////////////////////////////////////////////////////////
    /// VARIABLES
    
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    SwingWorker<Integer, InfoSequence>  loadSwingWorker; //SwingWorker to import sequence
    SwingWorker<Integer, Object>  loadSwingWorker2;     //SwingWorker to import sequence
    InformationJDialog loading;                        //Loading sequence JDialog
    Vector<InfoSequence>MultipleInfoSequence=new Vector<InfoSequence>();
    databaseFunction df=new databaseFunction();
    String old_filename="";
    ////////////////////////////////////////////////////////////////////////////
    /// CONSTANT
    
    public final String defaultNameString="Name";
    
    /** Creates new form propertiesJDialog */
    public loadFiles2Editor(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
        //connectorinfobox=new ConnectorInfoBox(parent); //--Used to display Connector info
        //--Initialize component
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        LAF_SendType_ButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Filename_jTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        type_jComboBox1 = new javax.swing.JComboBox();
        OkjButton = new javax.swing.JButton();
        CanceljButton = new javax.swing.JButton();
        LAF_Repeat_Label = new javax.swing.JLabel();
        LAF2_Repeat_button = new javax.swing.JRadioButton();
        LAF2_AllInOne_Button = new javax.swing.JRadioButton();
        LAF_AllInOne_Label = new javax.swing.JLabel();
        LAF2_AllInOne_Files_Panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LAF2_AFIOS_Files_List = new javax.swing.JList();
        LAF2_AFIOS_update_button = new javax.swing.JButton();
        LAF2_AFIOS_ANF_button = new javax.swing.JButton();
        LAF_ChooseOption_Label = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setTitle("Properties");
        setResizable(false);

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("Directory or file(s)");

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(Filename_jTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Filename_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Name");

        jButton4.setText("Rename");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamejTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Output type to generate");

        type_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TextFile", "SOLIDFile", "FastaFile", "Results", "Text", "GenomeFile", "FastqFile" }));
        type_jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(type_jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(type_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5))
        );

        OkjButton.setText("<html><b>Ok</b></html>");
        OkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkjButtonActionPerformed(evt);
            }
        });

        CanceljButton.setText("Cancel");
        CanceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanceljButtonActionPerformed(evt);
            }
        });

        LAF_Repeat_Label.setForeground(new java.awt.Color(255, 0, 0));
        LAF_Repeat_Label.setText("Note: This will be converted to a \"Repeat\" workflow");

        LAF_SendType_ButtonGroup.add(LAF2_Repeat_button);
        LAF2_Repeat_button.setText("Repeat Worflows");
        LAF2_Repeat_button.setName("LAF2_Repeat_button"); // NOI18N
        LAF2_Repeat_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAF2_Repeat_buttonActionPerformed(evt);
            }
        });

        LAF_SendType_ButtonGroup.add(LAF2_AllInOne_Button);
        LAF2_AllInOne_Button.setText("All Files In One Shot (ONLY supported by : Bowtie2,Bowtie)");
        LAF2_AllInOne_Button.setName("LAF2_AllInOne_Button"); // NOI18N
        LAF2_AllInOne_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAF2_AllInOne_ButtonActionPerformed(evt);
            }
        });

        LAF_AllInOne_Label.setForeground(new java.awt.Color(255, 0, 0));
        LAF_AllInOne_Label.setText("Note: This will send all files in one shot. Please choose Files or directory wisely.");
        LAF_AllInOne_Label.setName("LAF_AllInOne_Label"); // NOI18N

        jScrollPane3.setViewportView(LAF2_AFIOS_Files_List);

        LAF2_AFIOS_update_button.setText("Update Selected Files");
        LAF2_AFIOS_update_button.setName("LAF2_AFIOS_update_button"); // NOI18N
        LAF2_AFIOS_update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAF2_AFIOS_update_buttonActionPerformed(evt);
            }
        });

        LAF2_AFIOS_ANF_button.setText("Add New Files");
        LAF2_AFIOS_ANF_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAF2_AFIOS_ANF_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LAF2_AllInOne_Files_PanelLayout = new javax.swing.GroupLayout(LAF2_AllInOne_Files_Panel);
        LAF2_AllInOne_Files_Panel.setLayout(LAF2_AllInOne_Files_PanelLayout);
        LAF2_AllInOne_Files_PanelLayout.setHorizontalGroup(
            LAF2_AllInOne_Files_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAF2_AllInOne_Files_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LAF2_AFIOS_update_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF2_AFIOS_ANF_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LAF2_AllInOne_Files_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LAF2_AllInOne_Files_PanelLayout.setVerticalGroup(
            LAF2_AllInOne_Files_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAF2_AllInOne_Files_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAF2_AllInOne_Files_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAF2_AFIOS_update_button)
                    .addComponent(LAF2_AFIOS_ANF_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LAF_ChooseOption_Label.setForeground(new java.awt.Color(255, 0, 0));
        LAF_ChooseOption_Label.setText("Select an option. Anytime, a doubt => cancel and reopen");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LAF2_AllInOne_Files_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(CanceljButton)
                                .addGap(18, 18, 18)
                                .addComponent(OkjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAF2_Repeat_button)
                                    .addComponent(LAF_AllInOne_Label)
                                    .addComponent(LAF2_AllInOne_Button))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(LAF_ChooseOption_Label))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LAF_Repeat_Label)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF_ChooseOption_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF2_Repeat_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF_Repeat_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF2_AllInOne_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF_AllInOne_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LAF2_AllInOne_Files_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OkjButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CanceljButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Load All Files", jPanel9);

        jButton3.setText("?");
        jButton3.setToolTipText("Help / Informations");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        
}//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFileChooser jf;
        if (this.Filename_jTextField.getText().isEmpty()) {
            jf=new JFileChooser(config.getExplorerPath());
        } else {
            jf=new JFileChooser(this.Filename_jTextField.getText());
        }
        jf.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jf.setAcceptAllFileFilterUsed(false);
        jf.setMultiSelectionEnabled(true);
        int result=jf.showOpenDialog(this);
        //CAS 1: On reussi a choisir un fichier
        if (result==JFileChooser.APPROVE_OPTION) {
            //--Remove previous files in object
            cleanRepeatProperties();
            
            //--Save new filepath
            File[] files=jf.getSelectedFiles();
            String filesList = allFilesNames(files);
            
            // Automaticaly update jComboBox type of file(s) if it's possible
            updateTypeOfFile(filesList);
            
            if (properties.isSet(LAF2_Repeat_button.getName())) {
                addfilesInTheList(false);
            }
            if (properties.isSet(LAF2_AllInOne_Button.getName())) {
                cleanRepeatProperties();
                addfilesInTheList(true);
            }

        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
}//GEN-LAST:event_jButton3ActionPerformed

    private void OkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkjButtonActionPerformed
        //properties.put("inputname", this.Filename_jTextField.getText());
        this.setVisible(false);
    }//GEN-LAST:event_OkjButtonActionPerformed

    private void CanceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanceljButtonActionPerformed
        if (properties.isSet(LAF2_AllInOne_Button.getName())) {
            properties.remove(LAF2_AllInOne_Button.getName());
            properties.remove("inputAllNames");
        }
        if (properties.isSet(LAF2_Repeat_button.getName())) {
            cleanRepeatProperties();
        }
        this.setVisible(false);
    }//GEN-LAST:event_CanceljButtonActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        properties.put("Name", this.NamejTextField.getText());
        parent_workflow.updateCurrentWorkflow(properties);
}//GEN-LAST:event_jButton4ActionPerformed

    private void type_jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_jComboBox1ActionPerformed
        // 0. Sequences
        // 1. MultipleSequences
        // 2. Alignment
        if (properties.isSet("type")) properties.remove("type");
        properties.put("type", this.type_jComboBox1.getSelectedIndex());
}//GEN-LAST:event_type_jComboBox1ActionPerformed

    private void LAF2_Repeat_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAF2_Repeat_buttonActionPerformed
        // TODO add your handling code here:
        LAF_ChooseOption_Label.setVisible(false);
        if (properties.isSet(LAF2_AllInOne_Button.getName())) {
            addfilesInTheList(false);
        }
        properties.put(LAF2_Repeat_button.getName(),LAF2_Repeat_button.isSelected());
        optionLabelRepeatVisibility(true);
        directoryEnabled(true);
    }//GEN-LAST:event_LAF2_Repeat_buttonActionPerformed

    private void LAF2_AllInOne_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAF2_AllInOne_ButtonActionPerformed
        // TODO add your handling code here:
        LAF_ChooseOption_Label.setVisible(false);
        if (properties.isSet(LAF2_Repeat_button.getName())) {
            cleanRepeatProperties();
        }
        properties.put(LAF2_AllInOne_Button.getName(),LAF2_AllInOne_Button.isSelected());
        optionLabelRepeatVisibility(false);
        directoryEnabled(true);
    }//GEN-LAST:event_LAF2_AllInOne_ButtonActionPerformed

    private void LAF2_AFIOS_ANF_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAF2_AFIOS_ANF_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser jf;
        if (this.Filename_jTextField.getText().isEmpty()) {
            jf=new JFileChooser(config.getExplorerPath());
        } else {
            jf=new JFileChooser(this.Filename_jTextField.getText());
        }
        jf.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jf.setAcceptAllFileFilterUsed(false);
        jf.setMultiSelectionEnabled(true);
        int result=jf.showOpenDialog(this);
        //CAS 1: On reussi a choisir un fichier
        if (result==JFileChooser.APPROVE_OPTION) {
            //--Remove previous files in object
            cleanRepeatProperties();
            
            //--Save new filepath
            File[] files=jf.getSelectedFiles();
            String filesList = properties.get("inputAllNames");
            String tmpFilesList = allFilesNames(files);
            if (!tmpFilesList.equals("")) filesList=filesList+"<>"+tmpFilesList;
            
            // Automaticaly update jComboBox type of file(s) if it's possible
            updateTypeOfFile(filesList);
            addfilesInTheList(true);
            cleanRepeatProperties();
        }
    }//GEN-LAST:event_LAF2_AFIOS_ANF_buttonActionPerformed

    private void LAF2_AFIOS_update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAF2_AFIOS_update_buttonActionPerformed
        // TODO add your handling code here:
        updateList();
    }//GEN-LAST:event_LAF2_AFIOS_update_buttonActionPerformed
    
    ////////////////////////////////////////////////////////////////////////////
    /// FILES FUNCTIONS
    
    // Function to add file(s) in a list of files reprensented by a String
    private String addToFilesList (String list,String file) {
        String s = list;
        if (s.equals("")) s = file;
        else s = s+"<>"+file;
        return s;
    }
    
    // Function to found what kind of files are present in the files list
    private int whatFilesInFilesList (String list) {
        String[] listFiles = list.split("<>");
        int [] nbType = new int [this.type_jComboBox1.getItemCount()];
        for (int t : nbType) t = 0; 
        int y = 0;
        for (String listFile : listFiles) {
            y = typeOfFile(listFile);
            nbType[y]=nbType[y]+1;
        }
        return maxIntTable(nbType);
    }
        // Sub function of whatFilesInFilesList
        private int typeOfFile (String list) {
            int typeVal = 0;
            String s = list;
            String type = "";

            int pos1 = s.lastIndexOf(".");
            type = s.substring(pos1+1,s.length());

            if (!type.equals("")) typeVal=findTypeInt(type);

            return typeVal;
        }
            // Sub function of typeOfFile
            private int findTypeInt(String s){
                int type = 0;
                if (s.equals("fasta")||s.equals("fa")) type = 2;
                else if (s.equals("txt")) type = 3;
                else if (s.equals("bt2")||s.equals("ebwt")) type = 5;
                else if (s.equals("fastq")||s.equals("fq")) type = 6;
                return type;
            }
        
        // Sub function of whatFilesInFilesList
        private int maxIntTable(int [] tab){
            int max = tab[0];
            int pos = 0;
            for (int i = 1; i < tab.length; i++) {
                if (tab[i] > max) {
                    max = tab[i];
                    pos = i;
                }
            }
            return pos;
        }
        
        // obtain all files names and path in properties and string with <>
        private String allFilesNames(File[] files) {
            String s = "";
            properties.put("ForObjectID",properties.getID());
            if (files.length>1) {
                properties.put("Description", "Multiple files...");
                this.Filename_jTextField.setText("Multiple files...");
                //--Note we handle recursive directory
                for (File f:files) {
                    if (f.isDirectory()) {
                        s = extracFilesFromDir(f);
                    } else {
                        properties.put("For_"+f.getAbsolutePath(), "inputname");
                        s = addToFilesList(s,f.getAbsolutePath());
                    }
                }
            } else if (files.length==1&&!files[0].isDirectory()) {
                this.Filename_jTextField.setText(files[0].getAbsolutePath());
                properties.put("Description", files[0].getAbsolutePath());
                properties.put("inputname", files[0].getAbsolutePath());
                s = addToFilesList(s,files[0].getAbsolutePath());
            } else if (files.length==1&&files[0].isDirectory()) {
                this.Filename_jTextField.setText(files[0].getAbsolutePath());
                properties.put("Description", "Multiple files in "+files[0].getAbsolutePath());
                s = extracFilesFromDir(files[0]);
            } else {
                this.Filename_jTextField.setText("");
                properties.remove("ForObjectID",properties.getID());
            }
            return s;
        }
            // Sub function of allFilesNames
            // @parameter : File
            // @return : String List of file(s) separated with a <>
            private String extracFilesFromDir (File f) {
                String s = "";
                for (File f1:this.listDir(f)) {
                    properties.put("For_"+f1.getAbsolutePath(), "inputname");
                    s = addToFilesList(s,f1.getAbsolutePath());    
                }
                return s;
            }
                // Sub fonction of extracFilesFromDir
                // Function that return files from a directory
                public Vector<File> listDir(File f) {
                    Vector<File> toReturn=new Vector<File>();
                    for (File f2:f.listFiles()) {
                        if (f2.isDirectory()) {
                            toReturn.addAll(listDir(f2));
                        } else {
                            toReturn.add(f2);
                        }
                    }
                    return toReturn;
                }
                
        // Update the type of file(s)
        private void updateTypeOfFile (String s) {
            int typeOfFiles = 0;
            if (!s.equals("") && s.contains("<>")) {
                s = sortList(s);
                typeOfFiles = whatFilesInFilesList(s);
                properties.put("inputAllNames",s);
                addfilesInTheList(true);
            } else if (!s.equals("") && !s.contains("<>")) {
                typeOfFiles = findTypeInt(s);
                properties.put("inputAllNames",s);
            }
            this.type_jComboBox1.setSelectedIndex(typeOfFiles);
            properties.put("type", this.type_jComboBox1.getSelectedIndex());
        }
            //sub function of updateTypeOfFile
            private String sortList (String list) {
                String sIn = list;
                String sOut = "";
                String[] tab = sIn.split("<>");
                Arrays.sort(tab);
                for (int i = 0; i < tab.length; i++) {
                    sOut = addToFilesList(sOut,tab[i]);
                }
                return sOut;
            }

    ///////////////////////////////////////////////////////////////////////////
    /// SUB FUNCTIONS Visibility
    private void optionLabelRepeatVisibility (boolean enabled){
        boolean disabled = !enabled;
        this.LAF_Repeat_Label.setVisible(enabled);
        this.LAF_AllInOne_Label.setVisible(disabled);
        this.LAF2_AFIOS_Files_List.setVisible(disabled);
        this.LAF2_AllInOne_Files_Panel.setVisible(disabled);
    }
    
    private void directoryEnabled (boolean enabled){
        jPanel3.setVisible(enabled);
        Filename_jTextField.setEnabled(enabled);
        jButton6.setEnabled(enabled);
    }

    ///////////////////////////////////////////////////////////////////////////
    /// SUB FUNCTIONS Cleanning
    private void cleanRepeatProperties(){
        properties.remove(LAF2_Repeat_button.getName());
        Vector<String>keys=new Vector<String>();
        for (Object k:properties.keySet()) keys.add((String)k);
        for(String key:keys) {
            if (key.startsWith("For_")) properties.remove(key);
        }
        properties.remove("inputname");
        properties.remove("Description");
        properties.remove("ForObjectID");
        properties.remove("type");
    }

    private void addfilesInTheList (boolean enabled){
        if (enabled == true) {
            String[] tab = (properties.get("inputAllNames")).split("<>");
            LAF2_AFIOS_Files_List.setListData(tab);
            //LAF2_AFIOS_Files_List.setSelectionInterval(0,tab.length);
        } else {
            LAF2_AFIOS_Files_List.removeAll();
            properties.remove("inputAllNames");
            properties.remove("Description");
            properties.remove("ForObjectID");
            properties.remove("type");
        }
    }
    
    private void updateList () {
        String s = "";
        String t = "";
        int[] tabInt = this.LAF2_AFIOS_Files_List.getSelectedIndices();
        
        if (tabInt.length>0) {
            for (int i = 0; i < tabInt.length; i++) {
                t = LAF2_AFIOS_Files_List.getModel().getElementAt(tabInt[i]).toString();
                s = addToFilesList(s,t);
            }
            addfilesInTheList(false);
            properties.put("inputAllNames",s);
            addfilesInTheList(true);
        }
    }
    
    
    
    ///////////////////////////////////////////////////////////////////////////
    /// DISPLAY MAIN FUNCTION
    
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        setSettingForProperties();
        
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }

    /**
     * This set the different setting corresponding to the current properties
     */
    public void setSettingForProperties() {
        setTitle(properties.getName());
        this.NamejTextField.setText(properties.getName());
        
        LAF_ChooseOption_Label.setVisible(false);
        if (!properties.isSet(LAF2_Repeat_button.getName()) &&
                !properties.isSet(LAF2_AllInOne_Button.getName())) {
            directoryEnabled(false);
            this.LAF2_AllInOne_Files_Panel.setVisible(false);
            LAF_ChooseOption_Label.setVisible(true);
        }
        if (properties.isSet(LAF2_Repeat_button.getName())) {
            this.LAF2_Repeat_button.setSelected(true);
            this.properties.remove("inputAllNames");
            optionLabelRepeatVisibility(true);
            if (properties.isSet("inputname")) {
                this.Filename_jTextField.setText(properties.get("inputname"));
            }
            directoryEnabled(true);
        }
        if (properties.isSet(LAF2_AllInOne_Button.getName())) {
            this.Filename_jTextField.setText(properties.get("Description"));
            this.LAF2_AllInOne_Button.setSelected(true);
            optionLabelRepeatVisibility(false);
            directoryEnabled(true);
            if (properties.isSet("inputAllNames")) addfilesInTheList(true);
        }
        
        if (properties.isSet("type")) {
            this.type_jComboBox1.setSelectedIndex(properties.getInt("type"));
        }
    }

    @Override
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanceljButton;
    private javax.swing.JTextField Filename_jTextField;
    private javax.swing.JButton LAF2_AFIOS_ANF_button;
    private javax.swing.JList LAF2_AFIOS_Files_List;
    private javax.swing.JButton LAF2_AFIOS_update_button;
    private javax.swing.JRadioButton LAF2_AllInOne_Button;
    private javax.swing.JPanel LAF2_AllInOne_Files_Panel;
    private javax.swing.JRadioButton LAF2_Repeat_button;
    private javax.swing.JLabel LAF_AllInOne_Label;
    private javax.swing.JLabel LAF_ChooseOption_Label;
    private javax.swing.JLabel LAF_Repeat_Label;
    private javax.swing.ButtonGroup LAF_SendType_ButtonGroup;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JButton OkjButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox type_jComboBox1;
    // End of variables declaration//GEN-END:variables
    
    
    
}
