/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import editor.EditorInterface;
import configuration.Util;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author Jérémy Goimard
 * 
 */
public class miRcheck_evaluate_miRNA_candidates_Editors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form miRchekEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public miRcheck_evaluate_miRNA_candidates_Editors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        miRcheck = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        name_jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Options_panel = new javax.swing.JTabbedPane();
        Evaluate_panel = new javax.swing.JPanel();
        C_unpair_value = new javax.swing.JSpinner();
        C_starUnpair_value = new javax.swing.JSpinner();
        C_sizeDiff_value = new javax.swing.JSpinner();
        C_mirBulge_value = new javax.swing.JSpinner();
        C_starBulge_value = new javax.swing.JSpinner();
        C_fbackMin_value = new javax.swing.JSpinner();
        C_ass_value = new javax.swing.JSpinner();
        C_minUnpair_value = new javax.swing.JSpinner();
        C_bpExt_value = new javax.swing.JSpinner();
        C_starUnpair_box = new javax.swing.JCheckBox();
        C_sizeDiff_box = new javax.swing.JCheckBox();
        C_mirBulge_box = new javax.swing.JCheckBox();
        C_starBulge_box = new javax.swing.JCheckBox();
        C_fbackMin_box = new javax.swing.JCheckBox();
        C_ass_box = new javax.swing.JCheckBox();
        C_minUnpair_box = new javax.swing.JCheckBox();
        C_bpExt_box = new javax.swing.JCheckBox();
        C_unpair_box = new javax.swing.JCheckBox();
        reset_jButton3 = new javax.swing.JButton();
        stop_jButton4 = new javax.swing.JButton();
        run_jButton5 = new javax.swing.JButton();
        ClosejButton6 = new javax.swing.JButton();
        default_options_jbutton = new javax.swing.JRadioButton();
        advanced_options_jbutton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        miRcheck.setPreferredSize(new java.awt.Dimension(405, 604));
        miRcheck.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                miRcheckComponentShown(evt);
            }
        });

        jButton2.setText("Rename");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        name_jTextField1.setText("miRcheck evaluate miRNA candidates");

        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setPreferredSize(new java.awt.Dimension(381, 474));

        Options_panel.setPreferredSize(new java.awt.Dimension(341, 413));

        C_unpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_unpair_value.setName("E_minUnpair_value"); // NOI18N
        C_unpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_unpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_unpair_valueStateChanged(evt);
            }
        });

        C_starUnpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_starUnpair_value.setName("C_starUnpair_value"); // NOI18N
        C_starUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_starUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_starUnpair_valueStateChanged(evt);
            }
        });

        C_sizeDiff_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_sizeDiff_value.setName("C_sizeDiff_value"); // NOI18N
        C_sizeDiff_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_sizeDiff_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_sizeDiff_valueStateChanged(evt);
            }
        });

        C_mirBulge_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_mirBulge_value.setName("C_mirBulge_value"); // NOI18N
        C_mirBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_mirBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_mirBulge_valueStateChanged(evt);
            }
        });

        C_starBulge_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_starBulge_value.setName("C_starBulge_value"); // NOI18N
        C_starBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_starBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_starBulge_valueStateChanged(evt);
            }
        });

        C_fbackMin_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_fbackMin_value.setName("C_fbackMin_value"); // NOI18N
        C_fbackMin_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_fbackMin_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_fbackMin_valueStateChanged(evt);
            }
        });

        C_ass_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_ass_value.setName("C_ass_value"); // NOI18N
        C_ass_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_ass_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_ass_valueStateChanged(evt);
            }
        });

        C_minUnpair_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_minUnpair_value.setName("C_minUnpair_value"); // NOI18N
        C_minUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_minUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_minUnpair_valueStateChanged(evt);
            }
        });

        C_bpExt_value.setModel(new javax.swing.SpinnerNumberModel(-1, -1, null, 1));
        C_bpExt_value.setName("C_bpExt_value"); // NOI18N
        C_bpExt_value.setPreferredSize(new java.awt.Dimension(118, 28));
        C_bpExt_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                C_bpExt_valueStateChanged(evt);
            }
        });

        C_starUnpair_box.setText("star_unpair");
        C_starUnpair_box.setName("C_starUnpair_box"); // NOI18N
        C_starUnpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_starUnpair_boxActionPerformed(evt);
            }
        });

        C_sizeDiff_box.setText("size_diff");
        C_sizeDiff_box.setName("C_sizeDiff_box"); // NOI18N
        C_sizeDiff_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_sizeDiff_boxActionPerformed(evt);
            }
        });

        C_mirBulge_box.setText("mir_bulge");
        C_mirBulge_box.setName("C_mirBulge_box"); // NOI18N
        C_mirBulge_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_mirBulge_boxActionPerformed(evt);
            }
        });

        C_starBulge_box.setText("star_bulge");
        C_starBulge_box.setName("C_starBulge_box"); // NOI18N
        C_starBulge_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_starBulge_boxActionPerformed(evt);
            }
        });

        C_fbackMin_box.setText("fback_min");
        C_fbackMin_box.setName("C_fbackMin_box"); // NOI18N
        C_fbackMin_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_fbackMin_boxActionPerformed(evt);
            }
        });

        C_ass_box.setText("ass");
        C_ass_box.setName("C_ass_box"); // NOI18N
        C_ass_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ass_boxActionPerformed(evt);
            }
        });

        C_minUnpair_box.setText("min_unpair");
        C_minUnpair_box.setName("C_minUnpair_box"); // NOI18N
        C_minUnpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_minUnpair_boxActionPerformed(evt);
            }
        });

        C_bpExt_box.setText("bp_ext");
        C_bpExt_box.setName("C_bpExt_box"); // NOI18N
        C_bpExt_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_bpExt_boxActionPerformed(evt);
            }
        });

        C_unpair_box.setText("unpair");
        C_unpair_box.setName("C_unpair_box"); // NOI18N
        C_unpair_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_unpair_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Evaluate_panelLayout = new javax.swing.GroupLayout(Evaluate_panel);
        Evaluate_panel.setLayout(Evaluate_panelLayout);
        Evaluate_panelLayout.setHorizontalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_unpair_box)
                    .addComponent(C_starUnpair_box)
                    .addComponent(C_sizeDiff_box)
                    .addComponent(C_mirBulge_box)
                    .addComponent(C_starBulge_box)
                    .addComponent(C_fbackMin_box)
                    .addComponent(C_ass_box)
                    .addComponent(C_minUnpair_box)
                    .addComponent(C_bpExt_box))
                .addGap(18, 18, 18)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Evaluate_panelLayout.setVerticalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_unpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starUnpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_sizeDiff_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_mirBulge_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_starBulge_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_fbackMin_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_ass_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_minUnpair_box))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_bpExt_box))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Options_panel.addTab("advanced options", Evaluate_panel);

        reset_jButton3.setText("Reset default value");
        reset_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton3ActionPerformed(evt);
            }
        });

        stop_jButton4.setText("Stop");
        stop_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton4ActionPerformed(evt);
            }
        });

        run_jButton5.setText("Run");
        run_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton5ActionPerformed(evt);
            }
        });

        ClosejButton6.setText("Close");
        ClosejButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButton6ActionPerformed(evt);
            }
        });

        default_options_jbutton.setText("default options");
        default_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_options_jbuttonActionPerformed(evt);
            }
        });

        advanced_options_jbutton.setText("advanced options");
        advanced_options_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advanced_options_jbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(default_options_jbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(advanced_options_jbutton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(reset_jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop_jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run_jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClosejButton6))
                    .addComponent(Options_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(default_options_jbutton)
                    .addComponent(advanced_options_jbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_jButton3)
                    .addComponent(stop_jButton4)
                    .addComponent(run_jButton5)
                    .addComponent(ClosejButton6))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        miRcheck.addTab("miRcheck evaluate miRNA candidates", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(miRcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miRcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void miRcheckComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_miRcheckComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_miRcheckComponentShown

    private void ClosejButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ClosejButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton3ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
    }//GEN-LAST:event_reset_jButton3ActionPerformed

    private void stop_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton4ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton4ActionPerformed

    private void run_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton5ActionPerformed
        // TODO add your handling code here:
        if(properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton5ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        properties.put("Name", this.name_jTextField1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void C_unpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_unpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_unpair_valueStateChanged

    private void C_sizeDiff_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_sizeDiff_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_sizeDiff_box,C_sizeDiff_value);
    }//GEN-LAST:event_C_sizeDiff_valueStateChanged

    private void C_starUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_starUnpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_starUnpair_box,C_starUnpair_value);
    }//GEN-LAST:event_C_starUnpair_valueStateChanged

    private void C_mirBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_mirBulge_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_mirBulge_box,C_mirBulge_value);
    }//GEN-LAST:event_C_mirBulge_valueStateChanged

    private void C_starBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_starBulge_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_starBulge_box,C_starBulge_value);
    }//GEN-LAST:event_C_starBulge_valueStateChanged

    private void C_fbackMin_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_fbackMin_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_fbackMin_box,C_fbackMin_value);
    }//GEN-LAST:event_C_fbackMin_valueStateChanged

    private void C_ass_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_ass_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_ass_box,C_ass_value);
    }//GEN-LAST:event_C_ass_valueStateChanged

    private void C_minUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_minUnpair_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_minUnpair_box,C_minUnpair_value);
    }//GEN-LAST:event_C_minUnpair_valueStateChanged

    private void C_bpExt_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_C_bpExt_valueStateChanged
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_bpExt_box,C_bpExt_value);
    }//GEN-LAST:event_C_bpExt_valueStateChanged
 
    private void C_starUnpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_starUnpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_starUnpair_boxActionPerformed

    private void C_sizeDiff_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_sizeDiff_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_sizeDiff_boxActionPerformed

    private void C_mirBulge_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_mirBulge_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_mirBulge_boxActionPerformed

    private void C_starBulge_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_starBulge_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_starBulge_boxActionPerformed

    private void C_fbackMin_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_fbackMin_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_fbackMin_boxActionPerformed

    private void C_ass_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ass_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_ass_boxActionPerformed

    private void C_minUnpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_minUnpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_minUnpair_boxActionPerformed

    private void C_bpExt_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_bpExt_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_bpExt_boxActionPerformed

    private void C_unpair_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_unpair_boxActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,C_unpair_box,C_unpair_value);
    }//GEN-LAST:event_C_unpair_boxActionPerformed

    private void advanced_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advanced_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,advanced_options_jbutton,null);
        if (properties.isSet(default_options_jbutton.getName())) {
            properties.remove(default_options_jbutton.getName());
        }
        menuFields(properties);
    }//GEN-LAST:event_advanced_options_jbuttonActionPerformed

    private void default_options_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_default_options_jbuttonActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,default_options_jbutton,null);
        if (properties.isSet(advanced_options_jbutton.getName())) {
            properties.remove(advanced_options_jbutton.getName());
        }
        menuFields(properties);
    }//GEN-LAST:event_default_options_jbuttonActionPerformed
    
    /**
    ***************************************************************************
    * Set Properties
    ***************************************************************************
    */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues(properties);
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }
    
    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/
    
    private void updateSavedProperties(workflow_properties properties) {
        usp_valueANDtext (properties);
        usp_boxANDbutton (properties);
    }
    
    private void usp_valueANDtext (workflow_properties properties) {
        if (this.properties.isSet(C_ass_value.getName())){
            this.C_ass_value.setValue(Integer.parseInt(this.properties.get(C_ass_value.getName())));
            this.C_ass_value.setVisible(false);
        }
        if (this.properties.isSet(C_bpExt_value.getName())){
            this.C_bpExt_value.setValue(Integer.parseInt(this.properties.get(C_bpExt_value.getName())));
            this.C_bpExt_value.setVisible(false);
        }
        if (this.properties.isSet(C_fbackMin_value.getName())){
            this.C_fbackMin_value.setValue(Integer.parseInt(this.properties.get(C_fbackMin_value.getName())));
            this.C_fbackMin_value.setVisible(false);
        }
        if (this.properties.isSet(C_minUnpair_value.getName())){
            this.C_minUnpair_value.setValue(Integer.parseInt(this.properties.get(C_minUnpair_value.getName())));
            this.C_minUnpair_value.setVisible(false);
        }
        if (this.properties.isSet(C_mirBulge_value.getName())){
            this.C_mirBulge_value.setValue(Integer.parseInt(this.properties.get(C_mirBulge_value.getName())));
            this.C_mirBulge_value.setVisible(false);
        }
        if (this.properties.isSet(C_sizeDiff_value.getName())){
            this.C_sizeDiff_value.setValue(Integer.parseInt(this.properties.get(C_sizeDiff_value.getName())));
            this.C_sizeDiff_value.setVisible(false);
        }
        if (this.properties.isSet(C_starBulge_value.getName())){
            this.C_starBulge_value.setValue(Integer.parseInt(this.properties.get(C_starBulge_value.getName())));
            this.C_starBulge_value.setVisible(false);
        }
        if (this.properties.isSet(C_starUnpair_value.getName())){
            this.C_starUnpair_value.setValue(Integer.parseInt(this.properties.get(C_starUnpair_value.getName())));
            this.C_starUnpair_value.setVisible(false);
        }
        if (this.properties.isSet(C_unpair_value.getName())){
            this.C_unpair_value.setValue(Integer.parseInt(this.properties.get(C_unpair_value.getName())));
            this.C_unpair_value.setVisible(false);
        }
    }
    
    private void usp_boxANDbutton (workflow_properties properties) {
        if (this.properties.isSet(C_ass_box.getName())){
            this.C_ass_box.setSelected(true);
            this.C_ass_value.setEnabled(true);
        }
        if (this.properties.isSet(C_bpExt_box.getName())){
            this.C_bpExt_box.setSelected(true);
            this.C_bpExt_value.setEnabled(true);
        }
        if (this.properties.isSet(C_fbackMin_box.getName())){
            this.C_fbackMin_box.setSelected(true);
            this.C_fbackMin_value.setEnabled(true);
        }
        if (this.properties.isSet(C_minUnpair_box.getName())){
            this.C_minUnpair_box.setSelected(true);
            this.C_minUnpair_value.setEnabled(true);
        }
        if (this.properties.isSet(C_mirBulge_box.getName())){
            this.C_mirBulge_box.setSelected(true);
            this.C_mirBulge_value.setEnabled(true);
        }
        if (this.properties.isSet(C_sizeDiff_box.getName())){
            this.C_sizeDiff_box.setSelected(true);
            this.C_sizeDiff_value.setEnabled(true);
        }
        if (this.properties.isSet(C_starBulge_box.getName())){
            this.C_starBulge_box.setSelected(true);
            this.C_starBulge_value.setEnabled(true);
        }
        if (this.properties.isSet(C_starUnpair_box.getName())){
            this.C_starUnpair_box.setSelected(true);
            this.C_starUnpair_value.setEnabled(true);
        }
        if (this.properties.isSet(C_unpair_box.getName())){
            this.C_unpair_box.setSelected(true);
            this.C_unpair_value.setEnabled(true);
        }
    }
    
    /*******************************************************************
     * Set Menu fields
     ******************************************************************/
    
    private void menuFields(workflow_properties properties) {
        if (properties.isSet(default_options_jbutton.getName())) {
            enabled_Advanced_Options (false);
        }
        else if (properties.isSet(advanced_options_jbutton.getName())) {
            enabled_Advanced_Options (true);
        }
    }

    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabled_Advanced_Options (boolean e) {
        this.C_ass_box.setEnabled(e);
        if (properties.isSet(C_ass_box.getName()) && e==true) {
            this.C_ass_value.setEnabled(true);
        } else {
            properties.remove(C_ass_box.getName());
            this.C_ass_value.setEnabled(false);
        }
        
        this.C_bpExt_box.setEnabled(e);
        if (properties.isSet(C_bpExt_box.getName()) && e==true) {
            this.C_bpExt_value.setEnabled(true);
        } else {
            properties.remove(C_bpExt_box.getName());
            this.C_bpExt_value.setEnabled(false);
        }
        
        this.C_fbackMin_box.setEnabled(e);
        if (properties.isSet(C_fbackMin_box.getName()) && e==true) {
            this.C_fbackMin_value.setEnabled(true);
        } else {
            properties.remove(C_fbackMin_box.getName());
            this.C_fbackMin_value.setEnabled(false);
        }
        
        this.C_minUnpair_box.setEnabled(e);
        if (properties.isSet(C_minUnpair_box.getName()) && e==true) {
            this.C_minUnpair_value.setEnabled(true);
        } else {
            properties.remove(C_minUnpair_box.getName());
            this.C_minUnpair_value.setEnabled(false);
        }
        
        this.C_mirBulge_box.setEnabled(e);
        if (properties.isSet(C_mirBulge_box.getName()) && e==true) {
            this.C_mirBulge_value.setEnabled(true);
        } else {
            properties.remove(C_mirBulge_box.getName());
            this.C_mirBulge_value.setEnabled(false);
        }
        
        this.C_sizeDiff_box.setEnabled(e);
        if (properties.isSet(C_sizeDiff_box.getName()) && e==true) {
            this.C_sizeDiff_value.setEnabled(true);
        } else {
            properties.remove(C_sizeDiff_box.getName());
            this.C_sizeDiff_value.setEnabled(false);
        }
        
        this.C_starBulge_box.setEnabled(e);
        if (properties.isSet(C_starBulge_box.getName()) && e==true) {
            this.C_starBulge_value.setEnabled(true);
        } else {
            properties.remove(C_starBulge_box.getName());
            this.C_starBulge_value.setEnabled(false);
        }
        
        this.C_starUnpair_box.setEnabled(e);
        if (properties.isSet(C_starUnpair_box.getName()) && e==true) {
            this.C_starUnpair_value.setEnabled(true);
        } else {
            properties.remove(C_starUnpair_box.getName());
            this.C_starUnpair_value.setEnabled(false);
        }
        
        this.C_unpair_box.setEnabled(e);
        if (properties.isSet(C_unpair_box.getName()) && e==true) {
            this.C_unpair_value.setEnabled(true);
        } else {
            properties.remove(C_unpair_box.getName());
            this.C_unpair_value.setEnabled(false);
        }
    }
    
    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    private void defaultPgrmValues(workflow_properties properties) {
        boolean b = true;
        if (!(properties.isSet(default_options_jbutton.getName()))
        && !(properties.isSet(advanced_options_jbutton.getName()))
        ) {
            Util.buttonEventSpinner(properties,default_options_jbutton,null);
            default_options_jbutton.setSelected(true);
            b = false;
        }
        
        Util.getDefaultPgrmValues(properties,b);
    }
    
    /**
     * Set the configuration properties for this object
     */
    
    
    
    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setProperties(properties);
        this.updateSavedProperties(properties);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    @Override
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C_ass_box;
    private javax.swing.JSpinner C_ass_value;
    private javax.swing.JCheckBox C_bpExt_box;
    private javax.swing.JSpinner C_bpExt_value;
    private javax.swing.JCheckBox C_fbackMin_box;
    private javax.swing.JSpinner C_fbackMin_value;
    private javax.swing.JCheckBox C_minUnpair_box;
    private javax.swing.JSpinner C_minUnpair_value;
    private javax.swing.JCheckBox C_mirBulge_box;
    private javax.swing.JSpinner C_mirBulge_value;
    private javax.swing.JCheckBox C_sizeDiff_box;
    private javax.swing.JSpinner C_sizeDiff_value;
    private javax.swing.JCheckBox C_starBulge_box;
    private javax.swing.JSpinner C_starBulge_value;
    private javax.swing.JCheckBox C_starUnpair_box;
    private javax.swing.JSpinner C_starUnpair_value;
    private javax.swing.JCheckBox C_unpair_box;
    private javax.swing.JSpinner C_unpair_value;
    private javax.swing.JButton ClosejButton6;
    private javax.swing.JPanel Evaluate_panel;
    private javax.swing.JTabbedPane Options_panel;
    private javax.swing.JRadioButton advanced_options_jbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton default_options_jbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane miRcheck;
    private javax.swing.JTextField name_jTextField1;
    private javax.swing.JButton reset_jButton3;
    private javax.swing.JButton run_jButton5;
    private javax.swing.JButton stop_jButton4;
    // End of variables declaration//GEN-END:variables
}
