/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import editor.EditorInterface;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author Brisée-pas-morte
 */
public class miRcheckEditors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form MaqEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected="";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public miRcheckEditors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        BwaEditor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        name_jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mircheck_selected_ComboBox = new javax.swing.JComboBox();
        Options_panel = new javax.swing.JTabbedPane();
        Mircheck_panel = new javax.swing.JPanel();
        M_win_value = new javax.swing.JSpinner();
        M_unpair_value = new javax.swing.JSpinner();
        M_starUnpair_value = new javax.swing.JSpinner();
        M_sizeDiff_value = new javax.swing.JSpinner();
        M_mirBulge_value = new javax.swing.JSpinner();
        M_starBulge_value = new javax.swing.JSpinner();
        M_fbackMin_value = new javax.swing.JSpinner();
        M_ass_value = new javax.swing.JSpinner();
        M_bpExt_value = new javax.swing.JSpinner();
        M_minUnpair_value = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Patscan_panel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        P_db_text = new javax.swing.JTextField();
        P_mismatches_value = new javax.swing.JSpinner();
        P_deletions_value = new javax.swing.JSpinner();
        P_insertions_value = new javax.swing.JSpinner();
        IDG_change_button = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Evaluate_panel = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        E_unpair_value = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        E_starUnpair_value = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        E_sizeDiff_value = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        E_mirBulge_value = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        E_starBulge_value = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        E_fbackMin_value = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        E_ass_value = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        E_minUnpair_value = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        E_bpExt_value = new javax.swing.JSpinner();
        reset_jButton3 = new javax.swing.JButton();
        stop_jButton4 = new javax.swing.JButton();
        run_jButton5 = new javax.swing.JButton();
        ClosejButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BwaEditor.setPreferredSize(new java.awt.Dimension(405, 604));
        BwaEditor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BwaEditorComponentShown(evt);
            }
        });

        jButton2.setText("Rename");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        name_jTextField1.setText("miRcheck");

        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(name_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setPreferredSize(new java.awt.Dimension(381, 474));

        mircheck_selected_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "test_mircheck", "run_patscan", "evaluate_miRNA_candidates" }));
        mircheck_selected_ComboBox.setName("mircheck_selected_ComboBox"); // NOI18N
        mircheck_selected_ComboBox.setPreferredSize(new java.awt.Dimension(341, 27));
        mircheck_selected_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mircheck_selected_ComboBoxActionPerformed(evt);
            }
        });

        Options_panel.setPreferredSize(new java.awt.Dimension(341, 413));

        M_win_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_win_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_win_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_win_valueStateChanged(evt);
            }
        });

        M_unpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_unpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_unpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_unpair_valueStateChanged(evt);
            }
        });

        M_starUnpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_starUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_starUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_starUnpair_valueStateChanged(evt);
            }
        });

        M_sizeDiff_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_sizeDiff_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_sizeDiff_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_sizeDiff_valueStateChanged(evt);
            }
        });

        M_mirBulge_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_mirBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_mirBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_mirBulge_valueStateChanged(evt);
            }
        });

        M_starBulge_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_starBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_starBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_starBulge_valueStateChanged(evt);
            }
        });

        M_fbackMin_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_fbackMin_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_fbackMin_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_fbackMin_valueStateChanged(evt);
            }
        });

        M_ass_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_ass_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_ass_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_ass_valueStateChanged(evt);
            }
        });

        M_bpExt_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_bpExt_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_bpExt_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_bpExt_valueStateChanged(evt);
            }
        });

        M_minUnpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        M_minUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        M_minUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                M_minUnpair_valueStateChanged(evt);
            }
        });

        jLabel2.setText("win");

        jLabel3.setText("unpair");

        jLabel4.setText("star_unpair");

        jLabel5.setText("size_diff");

        jLabel6.setText("mir_bulge");

        jLabel7.setText("star_bulge");

        jLabel8.setText("fback_min");

        jLabel9.setText("ass");

        jLabel10.setText("min_unpair");

        jLabel11.setText("bp_ext");

        jLabel17.setText("All values setted at -1 will be ignored");

        javax.swing.GroupLayout Mircheck_panelLayout = new javax.swing.GroupLayout(Mircheck_panel);
        Mircheck_panel.setLayout(Mircheck_panelLayout);
        Mircheck_panelLayout.setHorizontalGroup(
            Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mircheck_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mircheck_panelLayout.createSequentialGroup()
                        .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M_win_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Mircheck_panelLayout.setVerticalGroup(
            Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mircheck_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_win_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Mircheck_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Options_panel.addTab("mircheck", Mircheck_panel);

        jLabel12.setText("DB");

        jLabel13.setText("mismatches");

        jLabel14.setText("deletions");

        jLabel15.setText("insertions");

        jLabel18.setText("All values setted at -1 will be ignored");

        P_db_text.setName("P_db_text"); // NOI18N
        P_db_text.setPreferredSize(new java.awt.Dimension(251, 27));

        P_mismatches_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        P_mismatches_value.setPreferredSize(new java.awt.Dimension(118, 28));
        P_mismatches_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                P_mismatches_valueStateChanged(evt);
            }
        });

        P_deletions_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        P_deletions_value.setPreferredSize(new java.awt.Dimension(118, 28));
        P_deletions_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                P_deletions_valueStateChanged(evt);
            }
        });

        P_insertions_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        P_insertions_value.setPreferredSize(new java.awt.Dimension(118, 28));
        P_insertions_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                P_insertions_valueStateChanged(evt);
            }
        });

        IDG_change_button.setText("Choose a file");
        IDG_change_button.setName("IDG_change_button"); // NOI18N
        IDG_change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDG_change_buttonActionPerformed(evt);
            }
        });

        jRadioButton1.setText("from file");

        jRadioButton2.setText("from workflow");

        javax.swing.GroupLayout Patscan_panelLayout = new javax.swing.GroupLayout(Patscan_panel);
        Patscan_panel.setLayout(Patscan_panelLayout);
        Patscan_panelLayout.setHorizontalGroup(
            Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patscan_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(Patscan_panelLayout.createSequentialGroup()
                        .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(50, 50, 50)
                        .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P_insertions_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_deletions_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P_mismatches_value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12)
                    .addComponent(jRadioButton2)
                    .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Patscan_panelLayout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IDG_change_button))
                        .addComponent(P_db_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        Patscan_panelLayout.setVerticalGroup(
            Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Patscan_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(P_mismatches_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(P_deletions_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(P_insertions_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Patscan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(IDG_change_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_db_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        Options_panel.addTab("patscan", Patscan_panel);

        jLabel28.setText("All values setted at -1 will be ignored");

        jLabel16.setText("unpair");

        E_unpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_unpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_unpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_unpair_valueStateChanged(evt);
            }
        });

        jLabel29.setText("star_unpair");

        E_starUnpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_starUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_starUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_starUnpair_valueStateChanged(evt);
            }
        });

        jLabel30.setText("size_diff");

        E_sizeDiff_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_sizeDiff_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_sizeDiff_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_sizeDiff_valueStateChanged(evt);
            }
        });

        jLabel31.setText("mir_bulge");

        E_mirBulge_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_mirBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_mirBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_mirBulge_valueStateChanged(evt);
            }
        });

        jLabel32.setText("star_bulge");

        E_starBulge_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_starBulge_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_starBulge_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_starBulge_valueStateChanged(evt);
            }
        });

        jLabel33.setText("fback_min");

        E_fbackMin_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_fbackMin_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_fbackMin_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_fbackMin_valueStateChanged(evt);
            }
        });

        jLabel34.setText("ass");

        E_ass_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_ass_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_ass_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_ass_valueStateChanged(evt);
            }
        });

        jLabel35.setText("min_unpair");

        E_minUnpair_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_minUnpair_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_minUnpair_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_minUnpair_valueStateChanged(evt);
            }
        });

        jLabel36.setText("bp_ext");

        E_bpExt_value.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));
        E_bpExt_value.setPreferredSize(new java.awt.Dimension(118, 28));
        E_bpExt_value.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                E_bpExt_valueStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Evaluate_panelLayout = new javax.swing.GroupLayout(Evaluate_panel);
        Evaluate_panel.setLayout(Evaluate_panelLayout);
        Evaluate_panelLayout.setHorizontalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(Evaluate_panelLayout.createSequentialGroup()
                        .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        Evaluate_panelLayout.setVerticalGroup(
            Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Evaluate_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_unpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_starUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_sizeDiff_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_mirBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_starBulge_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_fbackMin_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_ass_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_minUnpair_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Evaluate_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_bpExt_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        Options_panel.addTab("evaluate", Evaluate_panel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Options_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mircheck_selected_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mircheck_selected_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        reset_jButton3.setText("Reset default value");
        reset_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_jButton3ActionPerformed(evt);
            }
        });

        stop_jButton4.setText("Stop");
        stop_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_jButton4ActionPerformed(evt);
            }
        });

        run_jButton5.setText("Run");
        run_jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_jButton5ActionPerformed(evt);
            }
        });

        ClosejButton6.setText("Close");
        ClosejButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosejButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(reset_jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stop_jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(run_jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ClosejButton6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_jButton3)
                    .addComponent(stop_jButton4)
                    .addComponent(run_jButton5)
                    .addComponent(ClosejButton6))
                .addContainerGap())
        );

        BwaEditor.addTab("miRcheck", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(BwaEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BwaEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BwaEditor.getAccessibleContext().setAccessibleName("BwaEditors");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void BwaEditorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BwaEditorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_BwaEditorComponentShown

    private void ClosejButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosejButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_ClosejButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton3ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
    }//GEN-LAST:event_reset_jButton3ActionPerformed

    private void stop_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton4ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton4ActionPerformed

    private void run_jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton5ActionPerformed
        // TODO add your handling code here:
        if(properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
    }//GEN-LAST:event_run_jButton5ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        properties.put("Name", this.name_jTextField1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mircheck_selected_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mircheck_selected_ComboBoxActionPerformed
        // TODO add your handling code here:
        int i = mircheck_selected_ComboBox.getSelectedIndex();
        properties.put(mircheck_selected_ComboBox.getName(),Integer.toString(i));
        if (i>-1) Options_panel.setSelectedIndex(i);
        else Options_panel.setSelectedIndex(0);
    }//GEN-LAST:event_mircheck_selected_ComboBoxActionPerformed

    private void IDG_change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDG_change_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser d;

        if (this.P_db_text.getText().isEmpty()) {
            d=new JFileChooser(config.getExplorerPath());
        } else {
            d=new JFileChooser(this.P_db_text.getText());
        }

        d.setFileSelectionMode(JFileChooser.FILES_ONLY);
        d.setAcceptAllFileFilterUsed(false);
        d.setMultiSelectionEnabled(false);
        int result = d.showOpenDialog(this);

        if (result==JFileChooser.APPROVE_OPTION) {
            File dir = d.getSelectedFile();

            // Set the text
            String path = dir.getAbsolutePath();
            P_db_text.setText(path);
            properties.put(P_db_text.getName(),path);
        }
    }//GEN-LAST:event_IDG_change_buttonActionPerformed

    private void M_win_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_win_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_win_value);
    }//GEN-LAST:event_M_win_valueStateChanged

    private void M_unpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_unpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_unpair_value);
    }//GEN-LAST:event_M_unpair_valueStateChanged

    private void M_starUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_starUnpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_starUnpair_value);
    }//GEN-LAST:event_M_starUnpair_valueStateChanged

    private void M_sizeDiff_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_sizeDiff_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_starUnpair_value);
    }//GEN-LAST:event_M_sizeDiff_valueStateChanged

    private void M_mirBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_mirBulge_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_mirBulge_value);
    }//GEN-LAST:event_M_mirBulge_valueStateChanged

    private void M_starBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_starBulge_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_starBulge_value);
    }//GEN-LAST:event_M_starBulge_valueStateChanged

    private void M_fbackMin_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_fbackMin_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_fbackMin_value);
    }//GEN-LAST:event_M_fbackMin_valueStateChanged

    private void M_ass_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_ass_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_ass_value);
    }//GEN-LAST:event_M_ass_valueStateChanged

    private void M_minUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_minUnpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_minUnpair_value);
    }//GEN-LAST:event_M_minUnpair_valueStateChanged

    private void M_bpExt_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_M_bpExt_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(M_bpExt_value);
    }//GEN-LAST:event_M_bpExt_valueStateChanged

    private void P_mismatches_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_P_mismatches_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(P_mismatches_value);
    }//GEN-LAST:event_P_mismatches_valueStateChanged

    private void P_deletions_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_P_deletions_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(P_deletions_value);
    }//GEN-LAST:event_P_deletions_valueStateChanged

    private void P_insertions_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_P_insertions_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(P_insertions_value);
    }//GEN-LAST:event_P_insertions_valueStateChanged

    private void E_unpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_unpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_unpair_value);
    }//GEN-LAST:event_E_unpair_valueStateChanged

    private void E_sizeDiff_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_sizeDiff_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_sizeDiff_value);
    }//GEN-LAST:event_E_sizeDiff_valueStateChanged

    private void E_starUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_starUnpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_starUnpair_value);
    }//GEN-LAST:event_E_starUnpair_valueStateChanged

    private void E_mirBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_mirBulge_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_mirBulge_value);
    }//GEN-LAST:event_E_mirBulge_valueStateChanged

    private void E_starBulge_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_starBulge_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_starBulge_value);
    }//GEN-LAST:event_E_starBulge_valueStateChanged

    private void E_fbackMin_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_fbackMin_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_fbackMin_value);
    }//GEN-LAST:event_E_fbackMin_valueStateChanged

    private void E_ass_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_ass_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_ass_value);
    }//GEN-LAST:event_E_ass_valueStateChanged

    private void E_minUnpair_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_minUnpair_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_minUnpair_value);
    }//GEN-LAST:event_E_minUnpair_valueStateChanged

    private void E_bpExt_valueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_E_bpExt_valueStateChanged
        // TODO add your handling code here:
        spinnerUpdate(E_bpExt_value);
    }//GEN-LAST:event_E_bpExt_valueStateChanged
    
    /**
     * Update Values content
     * /!\ DONT FORGET TO ADD A NAME in the design for all /!\
     * @param Update_Values
     */
    //Spinner update
    private void spinnerUpdate(javax.swing.JSpinner s){
        properties.put(s.getName(),s.getValue());
    }    
    
    /**
    ***************************************************************************
    * Set Properties
    ***************************************************************************
    */
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues(properties);
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
        
        
    }
    /*
    ***************************************************************************
    * Update Saved Properties => usp_functions
    ***************************************************************************
    */
    
    private void updateSavedProperties(workflow_properties properties) {
        if (properties.isSet(E_ass_value.getName()))
            this.E_ass_value.setValue(Integer.parseInt(this.properties.get(E_ass_value.getName())));
        if (properties.isSet(E_bpExt_value.getName()))
            this.E_bpExt_value.setValue(Integer.parseInt(this.properties.get(E_bpExt_value.getName())));
        if (properties.isSet(E_fbackMin_value.getName()))
            this.E_fbackMin_value.setValue(Integer.parseInt(this.properties.get(E_fbackMin_value.getName())));
        if (properties.isSet(E_minUnpair_value.getName()))
            this.E_minUnpair_value.setValue(Integer.parseInt(this.properties.get(E_minUnpair_value.getName())));
        if (properties.isSet(E_mirBulge_value.getName()))
            this.E_mirBulge_value.setValue(Integer.parseInt(this.properties.get(E_mirBulge_value.getName())));
        if (properties.isSet(E_sizeDiff_value.getName()))
            this.E_sizeDiff_value.setValue(Integer.parseInt(this.properties.get(E_sizeDiff_value.getName())));
        if (properties.isSet(E_starBulge_value.getName()))
            this.E_starBulge_value.setValue(Integer.parseInt(this.properties.get(E_starBulge_value.getName())));
        if (properties.isSet(E_starUnpair_value.getName()))
            this.E_starUnpair_value.setValue(Integer.parseInt(this.properties.get(E_starUnpair_value.getName())));
        if (properties.isSet(E_unpair_value.getName()))
            this.E_unpair_value.setValue(Integer.parseInt(this.properties.get(E_unpair_value.getName())));
        if (properties.isSet(M_ass_value.getName()))
            this.M_ass_value.setValue(Integer.parseInt(this.properties.get(M_ass_value.getName())));
        if (properties.isSet(M_bpExt_value.getName()))
            this.M_bpExt_value.setValue(Integer.parseInt(this.properties.get(M_bpExt_value.getName())));
        if (properties.isSet(M_fbackMin_value.getName()))
            this.M_fbackMin_value.setValue(Integer.parseInt(this.properties.get(M_fbackMin_value.getName())));
        if (properties.isSet(M_minUnpair_value.getName()))
            this.M_minUnpair_value.setValue(Integer.parseInt(this.properties.get(M_minUnpair_value.getName())));
        if (properties.isSet(M_mirBulge_value.getName()))
            this.M_mirBulge_value.setValue(Integer.parseInt(this.properties.get(M_mirBulge_value.getName())));
        if (properties.isSet(M_sizeDiff_value.getName()))
            this.M_sizeDiff_value.setValue(Integer.parseInt(this.properties.get(M_sizeDiff_value.getName())));
        if (properties.isSet(M_starBulge_value.getName()))
            this.M_starBulge_value.setValue(Integer.parseInt(this.properties.get(M_starBulge_value.getName())));
        if (properties.isSet(M_starUnpair_value.getName()))
            this.M_starUnpair_value.setValue(Integer.parseInt(this.properties.get(M_starUnpair_value.getName())));
        if (properties.isSet(M_unpair_value.getName()))
            this.M_unpair_value.setValue(Integer.parseInt(this.properties.get(M_unpair_value.getName())));
        if (properties.isSet(M_win_value.getName()))
            this.M_win_value.setValue(Integer.parseInt(this.properties.get(M_win_value.getName())));
        if (properties.isSet(P_deletions_value.getName()))
            this.P_deletions_value.setValue(Integer.parseInt(this.properties.get(P_deletions_value.getName())));
        if (properties.isSet(P_insertions_value.getName()))
            this.P_insertions_value.setValue(Integer.parseInt(this.properties.get(P_insertions_value.getName())));
        if (properties.isSet(P_mismatches_value.getName()))
            this.P_mismatches_value.setValue(Integer.parseInt(this.properties.get(P_mismatches_value.getName())));
        if (properties.isSet(P_db_text.getName()))
            this.P_db_text.setText(this.properties.get(P_db_text.getName()));
        // Option Selected
        if (properties.isSet(mircheck_selected_ComboBox.getName()))
            this.mircheck_selected_ComboBox.setSelectedItem(this.properties.get(mircheck_selected_ComboBox.getName()));
    }
    
    
    /**
     * Set With default program values present in properties file
     */
    
    private void defaultPgrmValues(workflow_properties properties) {
        int y = mircheck_selected_ComboBox.getSelectedIndex();
        if ( y==-1 && properties.isSet("defaultPgrmValues")) {
            String defaultEditorStatus = this.properties.get("defaultPgrmValues");
            String[] arrayDefault = defaultEditorStatus.split("<>");
            int z = 0;
            for (int i =0 ; i < arrayDefault.length ; i=i+2){
                z = i;
                this.properties.put(arrayDefault[z],arrayDefault[z+1]);
            }
            Options_panel.setSelectedIndex(0);
        }
    }
    
    /**
     * Set the configuration properties for this object
     */
    
    
    
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        this.setProperties(properties);
        this.updateSavedProperties(properties);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BwaEditor;
    private javax.swing.JButton ClosejButton6;
    private javax.swing.JSpinner E_ass_value;
    private javax.swing.JSpinner E_bpExt_value;
    private javax.swing.JSpinner E_fbackMin_value;
    private javax.swing.JSpinner E_minUnpair_value;
    private javax.swing.JSpinner E_mirBulge_value;
    private javax.swing.JSpinner E_sizeDiff_value;
    private javax.swing.JSpinner E_starBulge_value;
    private javax.swing.JSpinner E_starUnpair_value;
    private javax.swing.JSpinner E_unpair_value;
    private javax.swing.JPanel Evaluate_panel;
    private javax.swing.JButton IDG_change_button;
    private javax.swing.JSpinner M_ass_value;
    private javax.swing.JSpinner M_bpExt_value;
    private javax.swing.JSpinner M_fbackMin_value;
    private javax.swing.JSpinner M_minUnpair_value;
    private javax.swing.JSpinner M_mirBulge_value;
    private javax.swing.JSpinner M_sizeDiff_value;
    private javax.swing.JSpinner M_starBulge_value;
    private javax.swing.JSpinner M_starUnpair_value;
    private javax.swing.JSpinner M_unpair_value;
    private javax.swing.JSpinner M_win_value;
    private javax.swing.JPanel Mircheck_panel;
    private javax.swing.JTabbedPane Options_panel;
    private javax.swing.JTextField P_db_text;
    private javax.swing.JSpinner P_deletions_value;
    private javax.swing.JSpinner P_insertions_value;
    private javax.swing.JSpinner P_mismatches_value;
    private javax.swing.JPanel Patscan_panel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JComboBox mircheck_selected_ComboBox;
    private javax.swing.JTextField name_jTextField1;
    private javax.swing.JButton reset_jButton3;
    private javax.swing.JButton run_jButton5;
    private javax.swing.JButton stop_jButton4;
    // End of variables declaration//GEN-END:variables
}
