/**
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

package editors;

import configuration.Config;
import configuration.Util;
import editor.EditorInterface;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import program.*;
import workflows.armadillo_workflow;
import workflows.workflow_properties;
import workflows.workflow_properties_dictionnary;

/**
 *
 * @author : Jérémy Goimard
 * @Date   : 10 115
 */

public class RNAfoldEditors extends javax.swing.JDialog implements EditorInterface  {
    
    /**
     * Creates new form RNAfoldEditors
     */
    Config config=new Config();
    //ConnectorInfoBox connectorinfobox;
    workflow_properties_dictionnary dict=new workflow_properties_dictionnary();
    String selected = "";             // Selected properties
    Frame frame;
    workflow_properties properties;
    armadillo_workflow  parent_workflow;
    
    public final String defaultNameString=" Name";
    static final boolean default_map=true;
    
    public RNAfoldEditors(java.awt.Frame parent, armadillo_workflow parent_workflow) {
        super(parent, false);
        this.parent_workflow=parent_workflow;
        //--Set variables and init
        frame=parent;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        how_jButton1 = new javax.swing.JButton();            //Basic Panel
        RNAfoldEditor = new javax.swing.JTabbedPane(); //Basic Panel
        general_jPanel1 = new javax.swing.JPanel();          //Basic Panel
        rename_jButton2 = new javax.swing.JButton();         //Basic Panel
        name_jTextField1 = new javax.swing.JTextField();     //Basic Panel
        name_jLabel1 = new javax.swing.JLabel();             //Basic Panel
        reset_jButton3 = new javax.swing.JButton();          //Basic Panel
        stop_jButton4 = new javax.swing.JButton();           //Basic Panel
        run_jButton5 = new javax.swing.JButton();            //Basic Panel
        close_jButton6 = new javax.swing.JButton();          //Basic Panel
        Default_Options_RButton = new javax.swing.JRadioButton();
        General_Options_RButton = new javax.swing.JRadioButton();
        Model_Details_RButton = new javax.swing.JRadioButton();
        AO_GO_constraint_Box = new javax.swing.JCheckBox();
        AO_GO_constraint_Box_Label = new javax.swing.JTextField();
        AO_GO_canonicalBPonly_Box = new javax.swing.JCheckBox();
        AO_GO_canonicalBPonly_Box_Label = new javax.swing.JTextField();
        AO_GO_noconv_Box = new javax.swing.JCheckBox();
        AO_GO_noconv_Box_Label = new javax.swing.JTextField();
        AO_GO_noPS_Box = new javax.swing.JCheckBox();
        AO_GO_noPS_Box_Label = new javax.swing.JTextField();
        AO_ASaawsbiitcTMfeaasraciac_partfunc_Box = new javax.swing.JCheckBox();
        AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value = new javax.swing.JSpinner();
        AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label = new javax.swing.JTextField();
        AO_ASaawsbiitcTMfeaasraciac_MEA_Box = new javax.swing.JCheckBox();
        AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value = new javax.swing.JSpinner();
        AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label = new javax.swing.JTextField();
        AO_ASaawsbiitcTMfeaasraciac_circ_Box = new javax.swing.JCheckBox();
        AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label = new javax.swing.JTextField();
        AO_ASaawsbiitcTMfeaasraciac_gquad_Box = new javax.swing.JCheckBox();
        AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label = new javax.swing.JTextField();
        AO_MD_temp_Box = new javax.swing.JCheckBox();
        AO_MD_temp_Box_Label = new javax.swing.JTextField();
        AO_MD_noTetra_Box = new javax.swing.JCheckBox();
        AO_MD_noTetra_Box_Label = new javax.swing.JTextField();
        AO_MD_dangles_Box = new javax.swing.JCheckBox();
        AO_MD_dangles_Box_Label = new javax.swing.JTextField();
        AO_MD_noLP_Box = new javax.swing.JCheckBox();
        AO_MD_noLP_Box_Label = new javax.swing.JTextField();
        AO_MD_noGU_Box = new javax.swing.JCheckBox();
        AO_MD_noGU_Box_Label = new javax.swing.JTextField();
        AO_MD_noClosingGU_Box = new javax.swing.JCheckBox();
        AO_MD_noClosingGU_Box_Label = new javax.swing.JTextField();
        AO_MD_paramFile_Box = new javax.swing.JCheckBox();
        AO_MD_paramFile_Box_Text = new javax.swing.JTextField();
        AO_panel = new javax.swing.JPanel();
        AO_ASaawsbiitcTMfeaasraciac_panel = new javax.swing.JPanel();
        AO_GO_panel = new javax.swing.JPanel();
        AO_MD_panel = new javax.swing.JPanel();
        AO_tabpanel = new javax.swing.JTabbedPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


            how_jButton1.setText("?");
            how_jButton1.setName("how_jButton1"); // NOI18N
            how_jButton1.getAccessibleContext().setAccessibleDescription("Calculate minimum free energy secondary structures and partition function of RNAs");
            how_jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    how_jButton1_ActionPerformed(evt);
                }
            });


            name_jTextField1.setText("RNAfoldEditor");
            name_jTextField1.setName("name_jTextField1"); // NOI18N
            name_jTextField1.getAccessibleContext().setAccessibleDescription("");
            name_jTextField1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    name_jTextField1_ActionPerformed(evt);
                }
            });


            rename_jButton2.setText("Rename");
            rename_jButton2.setName("rename_jButton2"); // NOI18N
            rename_jButton2.getAccessibleContext().setAccessibleDescription("Rename the box");
            rename_jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rename_jButton2_ActionPerformed(evt);
                }
            });


            reset_jButton3.setText("Reset");
            reset_jButton3.setName("reset_jButton3"); // NOI18N
            reset_jButton3.getAccessibleContext().setAccessibleDescription("Reset default value");
            reset_jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    reset_jButton3_ActionPerformed(evt);
                }
            });


            stop_jButton4.setText("Stop");
            stop_jButton4.setName("stop_jButton4"); // NOI18N
            stop_jButton4.getAccessibleContext().setAccessibleDescription("Stop the program");
            stop_jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    stop_jButton4_ActionPerformed(evt);
                }
            });


            run_jButton5.setText("Run");
            run_jButton5.setName("run_jButton5"); // NOI18N
            run_jButton5.getAccessibleContext().setAccessibleDescription("Run the program");
            run_jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    run_jButton5_ActionPerformed(evt);
                }
            });


            close_jButton6.setText("Close");
            close_jButton6.setName("close_jButton6"); // NOI18N
            close_jButton6.getAccessibleContext().setAccessibleDescription("Close this window");
            close_jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    close_jButton6_ActionPerformed(evt);
                }
            });


        general_jPanel1.setPreferredSize(new java.awt.Dimension(459,400));
        general_jPanel1.setName("general_jPanel1");

            Default_Options_RButton.setText("Default Options");
            Default_Options_RButton.setName("Default_Options_RButton"); // NOI18N
            Default_Options_RButton.getAccessibleContext().setAccessibleDescription("Default_Options");
            Default_Options_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Default_Options_RButton_ActionPerformed(evt);
                }
            });


            General_Options_RButton.setText("General Options");
            General_Options_RButton.setName("General_Options_RButton"); // NOI18N
            General_Options_RButton.getAccessibleContext().setAccessibleDescription("General_Options");
            General_Options_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    General_Options_RButton_ActionPerformed(evt);
                }
            });


            Model_Details_RButton.setText("Model Details");
            Model_Details_RButton.setName("Model_Details_RButton"); // NOI18N
            Model_Details_RButton.getAccessibleContext().setAccessibleDescription("Model_Details");
            Model_Details_RButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    Model_Details_RButton_ActionPerformed(evt);
                }
            });


        AO_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Advanced_Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N        AO_panel.setName("AO_panel"); // NOI18N

        AO_tabpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "AO_tabpanel"));
        AO_tabpanel.setName("AO_tabpanel"); // NOI18N
        AO_tabpanel.setPreferredSize(new java.awt.Dimension(280,280));
        AO_tabpanel.getAccessibleContext().setAccessibleName("AO_tabpanel");
        AO_tabpanel.addTab("General_Options", AO_GO_panel);
        AO_tabpanel.addTab("Algorithms_Select_additional_algorithms_which_should_be_included_in_the_calculations._The_Minimum_free_energy_(MFE)_and_a_structure_representative_are_calculated_in_any_case.", AO_ASaawsbiitcTMfeaasraciac_panel);
        AO_tabpanel.addTab("Model_Details", AO_MD_panel);

        AO_GO_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General_Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        AO_GO_panel.setName("AO_GO_panel"); // NOI18N
        

            AO_GO_constraint_Box.setText("constraint/-C");
            AO_GO_constraint_Box.setName("AO_GO_constraint_Box"); // NOI18N
            AO_GO_constraint_Box.getAccessibleContext().setAccessibleDescription("Calculate structures subject to constraints.");
            AO_GO_constraint_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_GO_constraint_Box_ActionPerformed(evt);
                }
            });


            AO_GO_constraint_Box_Label.setText("(default=off)");
            AO_GO_constraint_Box_Label.setName("AO_GO_constraint_Box_Label"); // NOI18N
            AO_GO_constraint_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_GO_constraint_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_GO_canonicalBPonly_Box.setText("canonicalBPonly");
            AO_GO_canonicalBPonly_Box.setName("AO_GO_canonicalBPonly_Box"); // NOI18N
            AO_GO_canonicalBPonly_Box.getAccessibleContext().setAccessibleDescription("Remove non-canonical base pairs from the structure constraint");
            AO_GO_canonicalBPonly_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_GO_canonicalBPonly_Box_ActionPerformed(evt);
                }
            });


            AO_GO_canonicalBPonly_Box_Label.setText("(default=off)");
            AO_GO_canonicalBPonly_Box_Label.setName("AO_GO_canonicalBPonly_Box_Label"); // NOI18N
            AO_GO_canonicalBPonly_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_GO_canonicalBPonly_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_GO_noconv_Box.setText("noconv");
            AO_GO_noconv_Box.setName("AO_GO_noconv_Box"); // NOI18N
            AO_GO_noconv_Box.getAccessibleContext().setAccessibleDescription("Do not automatically substitude nucleotide T with U");
            AO_GO_noconv_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_GO_noconv_Box_ActionPerformed(evt);
                }
            });


            AO_GO_noconv_Box_Label.setText("(default=off)");
            AO_GO_noconv_Box_Label.setName("AO_GO_noconv_Box_Label"); // NOI18N
            AO_GO_noconv_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_GO_noconv_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_GO_noPS_Box.setText("noPS");
            AO_GO_noPS_Box.setName("AO_GO_noPS_Box"); // NOI18N
            AO_GO_noPS_Box.getAccessibleContext().setAccessibleDescription("Do not produce postscript drawing of the mfe structure.");
            AO_GO_noPS_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_GO_noPS_Box_ActionPerformed(evt);
                }
            });


            AO_GO_noPS_Box_Label.setText("(default=off)");
            AO_GO_noPS_Box_Label.setName("AO_GO_noPS_Box_Label"); // NOI18N
            AO_GO_noPS_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_GO_noPS_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        AO_ASaawsbiitcTMfeaasraciac_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algorithms_Select_additional_algorithms_which_should_be_included_in_the_calculations._The_Minimum_free_energy_(MFE)_and_a_structure_representative_are_calculated_in_any_case.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        AO_ASaawsbiitcTMfeaasraciac_panel.setName("AO_ASaawsbiitcTMfeaasraciac_panel"); // NOI18N
        

            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.setText("partfunc/-p");
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.setName("AO_ASaawsbiitcTMfeaasraciac_partfunc_Box"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.getAccessibleContext().setAccessibleDescription("Calculate the partition function and base pairing probability matrix.");
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_ActionPerformed(evt);
                }
            });


            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label.setText("(default=`1')");
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label.setName("AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label.getAccessibleContext().setAccessibleDescription("(default=`1')");
            AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_ASaawsbiitcTMfeaasraciac_MEA_Box.setText("MEA");
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box.setName("AO_ASaawsbiitcTMfeaasraciac_MEA_Box"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box.getAccessibleContext().setAccessibleDescription("Calculate an MEA (maximum expected accuracy) structure, where the expected accuracy is computed from the pair probabilities: each base pair (i,j) gets a score 2*gamma*p_ij and the score of an unpaired base is given by the probability of not forming a pair.");
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_ASaawsbiitcTMfeaasraciac_MEA_Box_ActionPerformed(evt);
                }
            });


            AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label.setText("(default=`1.') [=gamma]");
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label.setName("AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label.getAccessibleContext().setAccessibleDescription("(default=`1.') [=gamma]");
            AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_ASaawsbiitcTMfeaasraciac_circ_Box.setText("circ/-c");
            AO_ASaawsbiitcTMfeaasraciac_circ_Box.setName("AO_ASaawsbiitcTMfeaasraciac_circ_Box"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_circ_Box.getAccessibleContext().setAccessibleDescription("Assume a circular (instead of linear) RNA molecule.");
            AO_ASaawsbiitcTMfeaasraciac_circ_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_ASaawsbiitcTMfeaasraciac_circ_Box_ActionPerformed(evt);
                }
            });


            AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label.setText("(default=off)");
            AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label.setName("AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_ASaawsbiitcTMfeaasraciac_gquad_Box.setText("gquad/-g");
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box.setName("AO_ASaawsbiitcTMfeaasraciac_gquad_Box"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box.getAccessibleContext().setAccessibleDescription("Incoorporate G-Quadruplex formation into the structure prediction algorithm");
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_ASaawsbiitcTMfeaasraciac_gquad_Box_ActionPerformed(evt);
                }
            });


            AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label.setText("(default=off)");
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label.setName("AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label"); // NOI18N
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        AO_MD_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Model_Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15))); // NOI18N
        AO_MD_panel.setName("AO_MD_panel"); // NOI18N
        

            AO_MD_temp_Box.setText("temp/-T");
            AO_MD_temp_Box.setName("AO_MD_temp_Box"); // NOI18N
            AO_MD_temp_Box.getAccessibleContext().setAccessibleDescription("Rescale energy parameters to a temperature of temp C.");
            AO_MD_temp_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_temp_Box_ActionPerformed(evt);
                }
            });


            AO_MD_temp_Box_Label.setText("Default is 37C. DOUBLE");
            AO_MD_temp_Box_Label.setName("AO_MD_temp_Box_Label"); // NOI18N
            AO_MD_temp_Box_Label.getAccessibleContext().setAccessibleDescription("Default is 37C. DOUBLE");
            AO_MD_temp_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_noTetra_Box.setText("noTetra/-4");
            AO_MD_noTetra_Box.setName("AO_MD_noTetra_Box"); // NOI18N
            AO_MD_noTetra_Box.getAccessibleContext().setAccessibleDescription("Do not include special tabulated stabilizing energies for tri-, tetra- and hexaloop hairpins. Mostly for testing.");
            AO_MD_noTetra_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_noTetra_Box_ActionPerformed(evt);
                }
            });


            AO_MD_noTetra_Box_Label.setText("(default=off)");
            AO_MD_noTetra_Box_Label.setName("AO_MD_noTetra_Box_Label"); // NOI18N
            AO_MD_noTetra_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_MD_noTetra_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_dangles_Box.setText("dangles/-d");
            AO_MD_dangles_Box.setName("AO_MD_dangles_Box"); // NOI18N
            AO_MD_dangles_Box.getAccessibleContext().setAccessibleDescription("How to treat dangling end energies for bases adjacent to helices in free ends and multi-loops");
            AO_MD_dangles_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_dangles_Box_ActionPerformed(evt);
                }
            });


            AO_MD_dangles_Box_Label.setText("(default=`2')");
            AO_MD_dangles_Box_Label.setName("AO_MD_dangles_Box_Label"); // NOI18N
            AO_MD_dangles_Box_Label.getAccessibleContext().setAccessibleDescription("(default=`2')");
            AO_MD_dangles_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_noLP_Box.setText("noLP");
            AO_MD_noLP_Box.setName("AO_MD_noLP_Box"); // NOI18N
            AO_MD_noLP_Box.getAccessibleContext().setAccessibleDescription("Produce structures without lonely pairs (helices of length 1).");
            AO_MD_noLP_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_noLP_Box_ActionPerformed(evt);
                }
            });


            AO_MD_noLP_Box_Label.setText("(default=off)");
            AO_MD_noLP_Box_Label.setName("AO_MD_noLP_Box_Label"); // NOI18N
            AO_MD_noLP_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_MD_noLP_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_noGU_Box.setText("noGU");
            AO_MD_noGU_Box.setName("AO_MD_noGU_Box"); // NOI18N
            AO_MD_noGU_Box.getAccessibleContext().setAccessibleDescription("Do not allow GU pairs");
            AO_MD_noGU_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_noGU_Box_ActionPerformed(evt);
                }
            });


            AO_MD_noGU_Box_Label.setText("(default=off)");
            AO_MD_noGU_Box_Label.setName("AO_MD_noGU_Box_Label"); // NOI18N
            AO_MD_noGU_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_MD_noGU_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_noClosingGU_Box.setText("noClosingGU");
            AO_MD_noClosingGU_Box.setName("AO_MD_noClosingGU_Box"); // NOI18N
            AO_MD_noClosingGU_Box.getAccessibleContext().setAccessibleDescription("Do not allow GU pairs at the end of helices");
            AO_MD_noClosingGU_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_noClosingGU_Box_ActionPerformed(evt);
                }
            });


            AO_MD_noClosingGU_Box_Label.setText("(default=off)");
            AO_MD_noClosingGU_Box_Label.setName("AO_MD_noClosingGU_Box_Label"); // NOI18N
            AO_MD_noClosingGU_Box_Label.getAccessibleContext().setAccessibleDescription("(default=off)");
            AO_MD_noClosingGU_Box_Label.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N

            AO_MD_paramFile_Box.setText("paramFile/-P");
            AO_MD_paramFile_Box.setName("AO_MD_paramFile_Box"); // NOI18N
            AO_MD_paramFile_Box.getAccessibleContext().setAccessibleDescription("Read energy parameters from paramfile, instead of using the default parameter set.");
            AO_MD_paramFile_Box.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AO_MD_paramFile_Box_ActionPerformed(evt);
                }
            });


    javax.swing.GroupLayout AO_panelLayout = new javax.swing.GroupLayout(AO_panel);
    AO_panel.setLayout(AO_panelLayout);
    AO_panelLayout.setHorizontalGroup(
        AO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AO_panelLayout.createSequentialGroup()
            .addContainerGap()
             .addComponent(AO_tabpanel)
            .addContainerGap() // truc
        )
    );
    AO_panelLayout.setVerticalGroup(
        AO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AO_panelLayout.createSequentialGroup()
            .addContainerGap()
             .addComponent(AO_tabpanel)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout AO_ASaawsbiitcTMfeaasraciac_panelLayout = new javax.swing.GroupLayout(AO_ASaawsbiitcTMfeaasraciac_panel);
    AO_ASaawsbiitcTMfeaasraciac_panel.setLayout(AO_ASaawsbiitcTMfeaasraciac_panelLayout);
    AO_ASaawsbiitcTMfeaasraciac_panelLayout.setHorizontalGroup(
        AO_ASaawsbiitcTMfeaasraciac_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AO_ASaawsbiitcTMfeaasraciac_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_circ_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_gquad_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap() // truc
        )
    );
    AO_ASaawsbiitcTMfeaasraciac_panelLayout.setVerticalGroup(
        AO_ASaawsbiitcTMfeaasraciac_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AO_ASaawsbiitcTMfeaasraciac_panelLayout.createSequentialGroup()
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_circ_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_gquad_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout AO_GO_panelLayout = new javax.swing.GroupLayout(AO_GO_panel);
    AO_GO_panel.setLayout(AO_GO_panelLayout);
    AO_GO_panelLayout.setHorizontalGroup(
        AO_GO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AO_GO_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(AO_GO_constraint_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_constraint_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_GO_canonicalBPonly_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_canonicalBPonly_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_GO_noconv_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noconv_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_GO_noPS_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noPS_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap() // truc
        )
    );
    AO_GO_panelLayout.setVerticalGroup(
        AO_GO_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AO_GO_panelLayout.createSequentialGroup()
            .addComponent(AO_GO_constraint_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_constraint_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_canonicalBPonly_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_canonicalBPonly_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noconv_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noconv_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noPS_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_GO_noPS_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout AO_MD_panelLayout = new javax.swing.GroupLayout(AO_MD_panel);
    AO_MD_panel.setLayout(AO_MD_panelLayout);
    AO_MD_panelLayout.setHorizontalGroup(
        AO_MD_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AO_MD_panelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(AO_MD_temp_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_temp_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_noTetra_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noTetra_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_dangles_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_dangles_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_noLP_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noLP_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_noGU_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noGU_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_noClosingGU_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noClosingGU_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap()
            .addComponent(AO_MD_paramFile_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_paramFile_Box_Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap() // truc
        )
    );
    AO_MD_panelLayout.setVerticalGroup(
        AO_MD_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AO_MD_panelLayout.createSequentialGroup()
            .addComponent(AO_MD_temp_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_temp_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noTetra_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noTetra_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_dangles_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_dangles_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noLP_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noLP_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noGU_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noGU_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noClosingGU_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_noClosingGU_Box_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_paramFile_Box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(AO_MD_paramFile_Box_Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

    javax.swing.GroupLayout AO_tabpanelLayout = new javax.swing.GroupLayout(AO_tabpanel);
    AO_tabpanel.setLayout(AO_tabpanelLayout);
    AO_tabpanelLayout.setHorizontalGroup(
        AO_tabpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AO_tabpanelLayout.createSequentialGroup()
            .addContainerGap()
            .addContainerGap()
            .addContainerGap()
            .addContainerGap() // truc
        )
    );
    AO_tabpanelLayout.setVerticalGroup(
        AO_tabpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(AO_tabpanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE) // truc
        )
    );

        RNAfoldEditor.setPreferredSize(new java.awt.Dimension(459,400));
        RNAfoldEditor.addTab("RNAfold Editor", general_jPanel1);
        RNAfoldEditor.getAccessibleContext().setAccessibleName("RNAfold");
        RNAfoldEditor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                RNAfoldEditorComponentShown(evt);
            }
        });
    

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(how_jButton1))
                    .addComponent(RNAfoldEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(how_jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RNAfoldEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RNAfoldEditorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_RNAfoldEditorComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_RNAfoldEditorComponentShown
    
    private void how_jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help_jButton1_ActionPerformed
        // TODO add your handling code here:
        HelpEditor help = new HelpEditor(this.frame, false, properties);
        help.setVisible(true);
    }//GEN-LAST:event_how_jButton1_ActionPerformed
    
    private void close_jButton6_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_jButton6_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_close_jButton6_ActionPerformed
    
    private void run_jButton5_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_jButton5_ActionPerformed
        // TODO add your handling code here:
        if (this.properties.isSet("ClassName")) {
            this.parent_workflow.workflow.updateDependance();
            programs prog=new programs(parent_workflow.workbox.getCurrentWorkflows());
            prog.Run(properties);
        }
    }//GEN-LAST:event_run_jButton5_ActionPerformed
    
    private void stop_jButton4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_jButton4_ActionPerformed
        // TODO add your handling code here:
        properties.put("Status", Config.status_nothing);
        properties.killThread();
    }//GEN-LAST:event_stop_jButton4_ActionPerformed
    
    private void reset_jButton3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_jButton3_ActionPerformed
        // TODO add your handling code here:
        properties.load();             //--reload current properties from file
        this.setProperties(properties);//--Update current field
        this.display(properties);
    }//GEN-LAST:event_reset_jButton3_ActionPerformed
    
    private void rename_jButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rename_jButton2_ActionPerformed
        // TODO add your handling code here:
        properties.put("Name", this.name_jTextField1.getText());
    }//GEN-LAST:event_rename_jButton2_ActionPerformed
    
    private void name_jTextField1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_jTextField1_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_jTextField1_ActionPerformed
    
    private void Default_Options_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Default_Options_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,Default_Options_RButton,null);
    }//GEN-LAST:event_Default_Options_RButton_ActionPerformed

    private void General_Options_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_General_Options_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,General_Options_RButton,null);
    }//GEN-LAST:event_General_Options_RButton_ActionPerformed

    private void Model_Details_RButton_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Model_Details_RButton_ActionPerformed
        // TODO add your handling code here:
        Util.buttonEventSpinner(properties,Model_Details_RButton,null);
    }//GEN-LAST:event_Model_Details_RButton_ActionPerformed

    private void AO_GO_constraint_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_GO_constraint_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_GO_constraint_Box,null);
    }//GEN-LAST:event_AO_GO_constraint_Box_ActionPerformed

    private void AO_GO_canonicalBPonly_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_GO_canonicalBPonly_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_GO_canonicalBPonly_Box,null);
    }//GEN-LAST:event_AO_GO_canonicalBPonly_Box_ActionPerformed

    private void AO_GO_noconv_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_GO_noconv_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_GO_noconv_Box,null);
    }//GEN-LAST:event_AO_GO_noconv_Box_ActionPerformed

    private void AO_GO_noPS_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_GO_noPS_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_GO_noPS_Box,null);
    }//GEN-LAST:event_AO_GO_noPS_Box_ActionPerformed

    private void AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_ASaawsbiitcTMfeaasraciac_partfunc_Box,AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value);
    }//GEN-LAST:event_AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_ActionPerformed

    private void AO_ASaawsbiitcTMfeaasraciac_MEA_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_ASaawsbiitcTMfeaasraciac_MEA_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_ASaawsbiitcTMfeaasraciac_MEA_Box,AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value);
    }//GEN-LAST:event_AO_ASaawsbiitcTMfeaasraciac_MEA_Box_ActionPerformed

    private void AO_ASaawsbiitcTMfeaasraciac_circ_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_ASaawsbiitcTMfeaasraciac_circ_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_ASaawsbiitcTMfeaasraciac_circ_Box,null);
    }//GEN-LAST:event_AO_ASaawsbiitcTMfeaasraciac_circ_Box_ActionPerformed

    private void AO_ASaawsbiitcTMfeaasraciac_gquad_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_ASaawsbiitcTMfeaasraciac_gquad_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_ASaawsbiitcTMfeaasraciac_gquad_Box,null);
    }//GEN-LAST:event_AO_ASaawsbiitcTMfeaasraciac_gquad_Box_ActionPerformed

    private void AO_MD_temp_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_temp_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_temp_Box,null);
    }//GEN-LAST:event_AO_MD_temp_Box_ActionPerformed

    private void AO_MD_noTetra_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_noTetra_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_noTetra_Box,null);
    }//GEN-LAST:event_AO_MD_noTetra_Box_ActionPerformed

    private void AO_MD_dangles_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_dangles_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_dangles_Box,null);
    }//GEN-LAST:event_AO_MD_dangles_Box_ActionPerformed

    private void AO_MD_noLP_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_noLP_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_noLP_Box,null);
    }//GEN-LAST:event_AO_MD_noLP_Box_ActionPerformed

    private void AO_MD_noGU_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_noGU_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_noGU_Box,null);
    }//GEN-LAST:event_AO_MD_noGU_Box_ActionPerformed

    private void AO_MD_noClosingGU_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_noClosingGU_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventSpinner(properties,AO_MD_noClosingGU_Box,null);
    }//GEN-LAST:event_AO_MD_noClosingGU_Box_ActionPerformed

    private void AO_MD_paramFile_Box_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AO_MD_paramFile_Box_ActionPerformed
        // TODO add your handling code here:
        Util.boxEventText(properties,AO_MD_paramFile_Box,AO_MD_paramFile_Box_Text);
    }//GEN-LAST:event_AO_MD_paramFile_Box_ActionPerformed
        
    /*******************************************************************
    * Enabled Function
    *******************************************************************/
    
    private void enabledFunction (boolean e) {
        this.AO_GO_constraint_Box.setEnabled(e);
        this.AO_GO_canonicalBPonly_Box.setEnabled(e);
        this.AO_GO_noconv_Box.setEnabled(e);
        this.AO_GO_noPS_Box.setEnabled(e);
        this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.setEnabled(e);
        if (properties.isSet(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.getName()) && e==true) {
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.setEnabled(true);
        } else {
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.setEnabled(false);
        }
        this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box.setEnabled(e);
        if (properties.isSet(AO_ASaawsbiitcTMfeaasraciac_MEA_Box.getName()) && e==true) {
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.setEnabled(true);
        } else {
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.setEnabled(false);
        }
        this.AO_ASaawsbiitcTMfeaasraciac_circ_Box.setEnabled(e);
        this.AO_ASaawsbiitcTMfeaasraciac_gquad_Box.setEnabled(e);
        this.AO_MD_temp_Box.setEnabled(e);
        this.AO_MD_noTetra_Box.setEnabled(e);
        this.AO_MD_dangles_Box.setEnabled(e);
        this.AO_MD_noLP_Box.setEnabled(e);
        this.AO_MD_noGU_Box.setEnabled(e);
        this.AO_MD_noClosingGU_Box.setEnabled(e);
        this.AO_MD_paramFile_Box.setEnabled(e);
        if (properties.isSet(AO_MD_paramFile_Box.getName()) && e==true) {
            this.AO_MD_paramFile_Box_Text.setEnabled(true);
        } else {
            this.AO_MD_paramFile_Box_Text.setEnabled(false);
        }
    }
    
    
    /*******************************************************************
    * Update Saved Properties => usp_functions
    *******************************************************************/
    
    private void updateSavedProperties(workflow_properties properties) {
        usp_valueANDtext (properties);
        usp_boxANDbutton (properties);
    }
    
    private void usp_valueANDtext (workflow_properties properties) {
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.setValue(Integer.parseInt(this.properties.get(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.getName())));
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.setEnabled(false);
        }
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.setValue(Integer.parseInt(this.properties.get(AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.getName())));
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.setEnabled(false);
        }
        if (this.properties.isSet(AO_MD_paramFile_Box_Text.getName())){
            this.AO_MD_paramFile_Box_Text.setText(this.properties.get(AO_MD_paramFile_Box_Text.getName()));
            this.AO_MD_paramFile_Box_Text.setEnabled(false);
        }
    }
    
    private void usp_boxANDbutton (workflow_properties properties) {
        if (this.properties.isSet(AO_GO_constraint_Box.getName())){
            this.AO_GO_constraint_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_GO_canonicalBPonly_Box.getName())){
            this.AO_GO_canonicalBPonly_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_GO_noconv_Box.getName())){
            this.AO_GO_noconv_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_GO_noPS_Box.getName())){
            this.AO_GO_noPS_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box.setSelected(true);
            this.AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value.setEnabled(true);
        }
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_MEA_Box.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box.setSelected(true);
            this.AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value.setEnabled(true);
        }
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_circ_Box.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_circ_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_ASaawsbiitcTMfeaasraciac_gquad_Box.getName())){
            this.AO_ASaawsbiitcTMfeaasraciac_gquad_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_temp_Box.getName())){
            this.AO_MD_temp_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_noTetra_Box.getName())){
            this.AO_MD_noTetra_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_dangles_Box.getName())){
            this.AO_MD_dangles_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_noLP_Box.getName())){
            this.AO_MD_noLP_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_noGU_Box.getName())){
            this.AO_MD_noGU_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_noClosingGU_Box.getName())){
            this.AO_MD_noClosingGU_Box.setSelected(true);
        }
        if (this.properties.isSet(AO_MD_paramFile_Box.getName())){
            this.AO_MD_paramFile_Box.setSelected(true);
            this.AO_MD_paramFile_Box_Text.setEnabled(true);
        }
    }
    

    /*******************************************************************
     * Set the configuration properties for this object
     ******************************************************************/
    
    @Override
    public void display(workflow_properties properties) {
        this.properties=properties;
        initComponents();
        setIconImage(Config.image);
        // Set position
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension d = getSize();
        setLocation((screenSize.width-d.width)/2,
                (screenSize.height-d.height)/2);
        
        // Set the program properties
        this.setProperties(properties);
        
        // Update Saved Properties => usp
        this.updateSavedProperties(properties);
        
        this.setAlwaysOnTop(true);
        this.setVisible(true);
    }
    
    /*******************************************************************
     * Sets for Properties
     ******************************************************************/
    
    /**
     * Set Properties
     * @param properties
     */
    
    public void setProperties(workflow_properties properties) {
        this.properties=properties;
        setTitle(properties.getName());
        //if (this.properties.isSet("Description")) this.Notice.setText(properties.get("Description"));
        
        // Properties Default Options
        this.defaultPgrmValues(properties);
        // Set the menu
        this.menuFields(properties);
    }
    
    public void setProperties(String filename, String path) {
        workflow_properties tmp=new workflow_properties();
        tmp.load(filename, path);
        this.properties=tmp;
        setTitle(properties.getName());
    }
    
    /*******************************************************************
     * Set With default program values present in properties file
     ******************************************************************/
    
    private void defaultPgrmValues(workflow_properties properties) {
        Util.getDefaultPgrmValues(properties,properties.isSet(Default_Options_RButton.getName()));
    }
        /*******************************************************************
     * Set Menu fields
     ******************************************************************/
    
    private void menuFields(workflow_properties properties) {
        if (properties.isSet(Default_Options_RButton.getName())) {
            Default_Options_RButton.setEnabled(true);
        }
        else if (properties.isSet(General_Options_RButton.getName())) {
            General_Options_RButton.setEnabled(true);
        }
        else if (properties.isSet(Model_Details_RButton.getName())) {
            Model_Details_RButton.setEnabled(true);
        }
    }
    
    /*******************************************************************
     * Save Image
     ******************************************************************/
    
    public void saveImage(String filename) {
        BufferedImage bi;
        try {
            bi = new Robot().createScreenCapture(this.getBounds());
            ImageIO.write(bi, "png", new File(filename));
            this.setVisible(false);
        } catch (Exception ex) {
            Config.log("Unable to save "+filename+" dialog image");
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton how_jButton1;           //Basic Panel
        private javax.swing.JTabbedPane RNAfoldEditor; //Basic Panel
        private javax.swing.JPanel general_jPanel1;         //Basic Panel
        private javax.swing.JButton rename_jButton2;        //Basic Panel
        private javax.swing.JTextField name_jTextField1;    //Basic Panel
        private javax.swing.JLabel name_jLabel1;            //Basic Panel
        private javax.swing.JButton reset_jButton3;         //Basic Panel
        private javax.swing.JButton stop_jButton4;          //Basic Panel
        private javax.swing.JButton run_jButton5;            //Basic Panel
        private javax.swing.JButton close_jButton6;          //Basic Panel
        private javax.swing.JRadioButton Default_Options_RButton;
        private javax.swing.JRadioButton General_Options_RButton;
        private javax.swing.JRadioButton Model_Details_RButton;
        private javax.swing.JCheckBox AO_GO_constraint_Box;
        private javax.swing.JTextField AO_GO_constraint_Box_Label;
        private javax.swing.JCheckBox AO_GO_canonicalBPonly_Box;
        private javax.swing.JTextField AO_GO_canonicalBPonly_Box_Label;
        private javax.swing.JCheckBox AO_GO_noconv_Box;
        private javax.swing.JTextField AO_GO_noconv_Box_Label;
        private javax.swing.JCheckBox AO_GO_noPS_Box;
        private javax.swing.JTextField AO_GO_noPS_Box_Label;
        private javax.swing.JCheckBox AO_ASaawsbiitcTMfeaasraciac_partfunc_Box;
        private javax.swing.JSpinner AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Value;
        private javax.swing.JTextField AO_ASaawsbiitcTMfeaasraciac_partfunc_Box_Label;
        private javax.swing.JCheckBox AO_ASaawsbiitcTMfeaasraciac_MEA_Box;
        private javax.swing.JSpinner AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Value;
        private javax.swing.JTextField AO_ASaawsbiitcTMfeaasraciac_MEA_Box_Label;
        private javax.swing.JCheckBox AO_ASaawsbiitcTMfeaasraciac_circ_Box;
        private javax.swing.JTextField AO_ASaawsbiitcTMfeaasraciac_circ_Box_Label;
        private javax.swing.JCheckBox AO_ASaawsbiitcTMfeaasraciac_gquad_Box;
        private javax.swing.JTextField AO_ASaawsbiitcTMfeaasraciac_gquad_Box_Label;
        private javax.swing.JCheckBox AO_MD_temp_Box;
        private javax.swing.JTextField AO_MD_temp_Box_Label;
        private javax.swing.JCheckBox AO_MD_noTetra_Box;
        private javax.swing.JTextField AO_MD_noTetra_Box_Label;
        private javax.swing.JCheckBox AO_MD_dangles_Box;
        private javax.swing.JTextField AO_MD_dangles_Box_Label;
        private javax.swing.JCheckBox AO_MD_noLP_Box;
        private javax.swing.JTextField AO_MD_noLP_Box_Label;
        private javax.swing.JCheckBox AO_MD_noGU_Box;
        private javax.swing.JTextField AO_MD_noGU_Box_Label;
        private javax.swing.JCheckBox AO_MD_noClosingGU_Box;
        private javax.swing.JTextField AO_MD_noClosingGU_Box_Label;
        private javax.swing.JCheckBox AO_MD_paramFile_Box;
        private javax.swing.JTextField AO_MD_paramFile_Box_Text;
        private javax.swing.JPanel AO_panel;
        private javax.swing.JPanel AO_ASaawsbiitcTMfeaasraciac_panel;
        private javax.swing.JPanel AO_GO_panel;
        private javax.swing.JPanel AO_MD_panel;
        private javax.swing.JTabbedPane AO_tabpanel;
    // End of variables declaration//GEN-END:variables
}
